### Sign up a new user with invalid password
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "password123"
}

### Sign up a new user with valid password
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "password123#"
}

### Sign in with existing user
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}

### Post profile of authenticated user
  POST http://localhost:3000/api/v1/auth/me
  Content-Type: application/json



